name: .NET Build Test

on:  
  push:
    branches: [ wip ]
  pull_request:
    branches: [ wip ]

jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE
        run: cd ConsoleApp1

      - name: Restore Packages
        run: nuget restore ConsoleApp1.sln

      - name: Build Solution
        run: |
          msbuild.exe ConsoleApp1.sln /p:platform="Any CPU" /p:configuration="Release"
          echo "Build complete!"